-- Finale MHD-App Datenbankstruktur
-- In Supabase SQL Editor ausführen.

create table if not exists public.mitarbeiter (
  id bigint generated by default as identity primary key,
  nummer text unique not null,
  passwort text not null,
  name text not null,
  rolle text default 'Mitarbeiter' check (rolle in ('Chef','Stationsleitung','Mitarbeiter')),
  aktiv boolean default true,
  muss_passwort_aendern boolean default true,
  created_at timestamp with time zone default now()
);

create table if not exists public.mhd_artikel (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  artikel text not null,
  barcode text,
  kategorie text default 'Sonstiges',
  mhd date not null,
  menge integer default 1,
  bild_url text,
  mitarbeiter text,
  created_by text
);

create table if not exists public.abschriften (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  artikel text not null,
  barcode text,
  kategorie text,
  mhd date,
  menge integer default 1,
  grund text not null,
  mitarbeiter text,
  bild_url text
);

-- Einfach für internen Tankstellenbetrieb: RLS aus, weil App eigenen Mitarbeiterlogin nutzt.
alter table public.mitarbeiter disable row level security;
alter table public.mhd_artikel disable row level security;
alter table public.abschriften disable row level security;

-- Beispiel-Mitarbeiter, später ändern/löschen.
alter table public.mitarbeiter add column if not exists rolle text default 'Mitarbeiter';

insert into public.mitarbeiter (nummer, passwort, name, rolle, muss_passwort_aendern)
values
  ('1','0000','Denis','Mitarbeiter', true),
  ('2','0000','Michael','Chef', true),
  ('3','0000','Chris','Stationsleitung', true),
  ('4','0000','Tizi','Mitarbeiter', true),
  ('5','0000','Philip','Mitarbeiter', true),
  ('6','0000','Anne','Mitarbeiter', true),
  ('7','0000','Lars','Mitarbeiter', true),
  ('8','0000','Mira','Mitarbeiter', true)
on conflict (nummer) do update set name=excluded.name, rolle=excluded.rolle;

-- Storage Bucket für eigene Produktbilder. Falls Fehler kommt: in Supabase Storage manuell Bucket artikelbilder public erstellen.
insert into storage.buckets (id, name, public)
values ('artikelbilder', 'artikelbilder', true)
on conflict (id) do nothing;


-- Falls die Tabelle schon existiert, diese Zeile ausführen, damit der Passwortwechsel funktioniert:
alter table public.mitarbeiter add column if not exists muss_passwort_aendern boolean default true;

-- Alle bestehenden Mitarbeiter auf Startpasswort 0000 setzen (optional, nur wenn gewünscht):
-- update public.mitarbeiter set passwort = '0000', muss_passwort_aendern = true;

-- Rollen später ändern Beispiel:
-- update public.mitarbeiter set rolle = 'Stationsleitung' where nummer = '3';
-- Mitarbeiter deaktivieren Beispiel:
-- update public.mitarbeiter set aktiv = false where nummer = '8';
